apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1 
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: ngnix-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]
  - name: cloudlens
    image: ixiacom/cloudlens-sandbox-agent
    args:
       - '--server'
       - agent.ixia.cloud
       - '--apikey'
       - s73VYBD9oNc5o7Q6kGKdks8467YSeyFFr44ey8fzA
       - '--custom_tags'
       - app=kube
       - '--accept_eula'
       - 'y'
    securityContext:
    capabilities:
    add:
       - SYS_RAWIO
       - SYS_ADMIN
       - NET_ADMIN
